.MODEL SMALL
.STACK 100H
.DATA
	LF EQU 0AH
	CR EQU 0DH
	LEN DB "LENGTH:",LF,CR,"$"
	ARG DB " ",LF,CR,"ARGUEMENTS ARE: ","$"
	L DW 0  ; A VARIABLE STORING LENGTH
	BASE DW 10
.CODE
MAIN PROC
;PSP - PROGRAM SEGMENT PREFIX
MOV BX,80H   ; AT 80H OFFSET THE LENGTH OF THE COMMAND LINE IS STORED
MOV CL,[BX]  ; LENGTH IS STORED IN CL
MOV CH,0

MOV AX,@DATA
MOV DS,AX   

LEA DX,LEN  
MOV AH,09H
INT 21H 

MOV DX,'$'
PUSH DX

MOV DX,0
MOV AX,0
MOV AL,CL  
MOV L,AX  

PUSH_DATA:   ;PRINTING THE LENGTH OF THE ARGUEMENT
	CMP AX,0
	JE PRINT
	DIV BASE
	PUSH DX
	MOV DX,0
	JMP PUSH_DATA

PRINT:
	POP DX
	CMP DX,'$'
	JE ARGUE
	ADD DX,48
	MOV AH,02H
	INT 21H
	JMP PRINT

ARGUE:
LEA DX,ARG
MOV AH,09H
INT 21H

MOV AH,62H
INT 21H
MOV DS,BX ; LOADING THE PSP TO BX

MOV CH,'$' 
MOV AX,0
MOV AL,CL  ; STORING THE LENGTH IN AX
MOV DI,AX ; STORING THE LENGTH IN DI

MOV AX,BX ; MOVING THE STARTING ADRESS OF PSP IN AX
MOV BX,DI ; MOVING LENGTH IN BX
MOV SI,81H ; SI HAS NOW THE STARTING ADRESS OF ARGUEMENT STRING 
MOV DS:[BX+SI],CH ; TERMINATING THE STRING
MOV DX,SI
MOV AH,09H
INT 21H

EXIT:
MOV AH,4CH 
INT 21H

MAIN ENDP
END MAIN